import { PlanPhase } from "./plan";

export const OWEN_PLAN: PlanPhase[] = [
  {
    id: "op1",
    name: "Base Build",
    range: "24 Aug – 6 Sep",
    note: "Consolidate the current ~58km base, add the first back-to-back long-run weekend, and start weekly downhill cadence drills — the single biggest technical lever on race time given the trail cadence data.",
    weeks: [
      {
        id: "ow1",
        label: "Week 1",
        dateRange: "24–30 Aug",
        sessions: [
          { date: "2026-08-24", type: "rest", label: "Rest" },
          { date: "2026-08-25", type: "run", label: "Run 12km, easy", targetKm: 12 },
          { date: "2026-08-26", type: "run", label: "Run 10km, easy", targetKm: 10 },
          { date: "2026-08-27", type: "run", label: "Trail 10km — downhill cadence drill, metronome 168–172spm", targetKm: 10 },
          { date: "2026-08-28", type: "gymL", label: "Strength — lower body + core" },
          { date: "2026-08-28", type: "run", label: "Easy 20min shakeout", targetMin: 20 },
          { date: "2026-08-29", type: "long", label: "Long trail 22km, ~500m vert — PH1000 from km1, 70g carb/hr", targetKm: 22 },
          { date: "2026-08-30", type: "long", label: "Back-to-back: easy trail 12km, tired legs", targetKm: 12 },
        ],
      },
      {
        id: "ow2",
        label: "Week 2",
        dateRange: "31 Aug – 6 Sep",
        sessions: [
          { date: "2026-08-31", type: "rest", label: "Rest or 20min mobility" },
          { date: "2026-09-01", type: "run", label: "Hill reps 6×90sec hard, jog-down recovery" },
          { date: "2026-09-02", type: "gymU", label: "Strength — upper + core" },
          { date: "2026-09-02", type: "run", label: "Easy 8km", targetKm: 8 },
          { date: "2026-09-03", type: "run", label: "Trail 12km — downhill cadence drill", targetKm: 12 },
          { date: "2026-09-04", type: "rest", label: "Rest" },
          { date: "2026-09-05", type: "long", label: "Long trail 26km, ~650m vert — PH1000 + carb protocol", targetKm: 26 },
          { date: "2026-09-06", type: "long", label: "Back-to-back: trail 14km, tired legs", targetKm: 14 },
        ],
      },
    ],
  },
  {
    id: "op2",
    name: "Altitude Block",
    range: "7 – 27 Sep",
    note: "A cutback week to travel fresh, then the Queenstown/Wanaka block: altitude adaptation, two signature vert sessions at Ben Lomond and Roy's Peak, snowboarding as active recovery on the days between.",
    weeks: [
      {
        id: "ow3",
        label: "Week 3 — travel week",
        dateRange: "7–13 Sep",
        sessions: [
          { date: "2026-09-07", type: "run", label: "Easy 8km", targetKm: 8 },
          { date: "2026-09-08", type: "run", label: "Run 8km w/ 4×3min strides", targetKm: 8 },
          { date: "2026-09-09", type: "gymL", label: "Strength — light" },
          { date: "2026-09-09", type: "run", label: "Easy 6km", targetKm: 6 },
          { date: "2026-09-10", type: "run", label: "Easy 10km, flat", targetKm: 10 },
          { date: "2026-09-11", type: "other", label: "Rest, pack for Queenstown" },
          { date: "2026-09-12", type: "run", label: "Easy 6km, legs loose", targetKm: 6 },
          { date: "2026-09-13", type: "other", label: "Travel day — fly to Queenstown" },
        ],
      },
      {
        id: "ow4",
        label: "Week 4 — Queenstown wk1",
        dateRange: "14–20 Sep",
        sessions: [
          { date: "2026-09-14", type: "run", label: "Easy 8km, shakeout — expect altitude HR drift", targetKm: 8 },
          { date: "2026-09-15", type: "other", label: "Snowboard — Coronet Peak (active recovery)" },
          { date: "2026-09-16", type: "run", label: "Trail 10km — Ben Lomond lower slopes, downhill cadence focus", targetKm: 10 },
          { date: "2026-09-17", type: "other", label: "Snowboard — The Remarkables (active recovery)" },
          { date: "2026-09-18", type: "rest", label: "Rest" },
          { date: "2026-09-19", type: "long", label: "Long trail — Ben Lomond summit, 20km/~1350m vert, PH1000 + carb protocol", targetKm: 20 },
          { date: "2026-09-20", type: "long", label: "Back-to-back: easy 10km, tired legs", targetKm: 10 },
        ],
      },
      {
        id: "ow5",
        label: "Week 5 — Queenstown wk2",
        dateRange: "21–27 Sep",
        sessions: [
          { date: "2026-09-21", type: "rest", label: "Rest" },
          { date: "2026-09-22", type: "other", label: "Snowboard — Treble Cone (active recovery)" },
          { date: "2026-09-23", type: "run", label: "Easy 8km, flat", targetKm: 8 },
          { date: "2026-09-24", type: "other", label: "Snowboard — Cardrona (active recovery)" },
          { date: "2026-09-25", type: "long", label: "Long trail — Roy's Peak, 22km/~1300m vert, PH1000 + carb protocol", targetKm: 22 },
          { date: "2026-09-26", type: "other", label: "Travel day — fly home" },
          { date: "2026-09-27", type: "run", label: "Easy 8km, reintroduce sea-level legs", targetKm: 8 },
        ],
      },
    ],
  },
  {
    id: "op3",
    name: "Peak Build",
    range: "28 Sep – 11 Oct",
    note: "Rebuild volume post-altitude, then the biggest week of the whole block: the South Boundary Road long run (~43.8km) as the closest full dress rehearsal for pacing, fuelling and sodium ahead of the peak volume block.",
    weeks: [
      {
        id: "ow6",
        label: "Week 6 — reintegration",
        dateRange: "28 Sep – 4 Oct",
        sessions: [
          { date: "2026-09-28", type: "rest", label: "Rest" },
          { date: "2026-09-29", type: "run", label: "Run 10km w/ 5×3min tempo @ ~4:35/km (LT effort)", targetKm: 10 },
          { date: "2026-09-30", type: "gymL", label: "Strength — lower + core" },
          { date: "2026-09-30", type: "run", label: "Easy 8km", targetKm: 8 },
          { date: "2026-10-01", type: "run", label: "Trail 14km — downhill cadence drill", targetKm: 14 },
          { date: "2026-10-02", type: "rest", label: "Rest" },
          { date: "2026-10-03", type: "long", label: "Long trail 28km, ~700m vert — PH1000 + carb protocol", targetKm: 28 },
          { date: "2026-10-04", type: "long", label: "Back-to-back: trail 16km, tired legs", targetKm: 16 },
        ],
      },
      {
        id: "ow7",
        label: "Week 7 — peak week",
        dateRange: "5–11 Oct",
        sessions: [
          { date: "2026-10-05", type: "rest", label: "Rest" },
          { date: "2026-10-06", type: "run", label: "Run 12km, easy", targetKm: 12 },
          { date: "2026-10-07", type: "gymU", label: "Strength — upper + core" },
          { date: "2026-10-07", type: "run", label: "Easy 8km", targetKm: 8 },
          { date: "2026-10-08", type: "run", label: "Trail 10km — downhill cadence drill, easy effort ahead of Sat", targetKm: 10 },
          { date: "2026-10-09", type: "other", label: "Rest, pre-long-run prep — check kit, fuel, PH1000 stock" },
          { date: "2026-10-10", type: "long", label: "South Boundary Road Trail, ~43.8km — full race-day fuel + sodium protocol", targetKm: 43.8 },
          { date: "2026-10-11", type: "other", label: "Recovery: 20min walk or easy spin only" },
        ],
      },
    ],
  },
  {
    id: "op4",
    name: "Consolidation",
    range: "12 – 25 Oct",
    note: "A lighter week to absorb the South Boundary Road effort, a long training run in place of a tune-up race, then a full recovery week before the peak volume block.",
    weeks: [
      {
        id: "ow8",
        label: "Week 8 — long run week",
        dateRange: "12–18 Oct",
        sessions: [
          { date: "2026-10-12", type: "run", label: "Easy 8km", targetKm: 8 },
          { date: "2026-10-13", type: "run", label: "Run 6km w/ 4×2min strides", targetKm: 6 },
          { date: "2026-10-14", type: "rest", label: "Rest" },
          { date: "2026-10-15", type: "run", label: "Easy 6km, legs loose", targetKm: 6 },
          { date: "2026-10-16", type: "rest", label: "Rest" },
          { date: "2026-10-17", type: "long", label: "Long trail 25km, ~600m vert — steady effort, fuel practice", targetKm: 25 },
          { date: "2026-10-18", type: "run", label: "Easy 10km recovery", targetKm: 10 },
        ],
      },
      {
        id: "ow9",
        label: "Week 9 — recovery",
        dateRange: "19–25 Oct",
        sessions: [
          { date: "2026-10-19", type: "other", label: "Rest, review the week — recalibrate pacing" },
          { date: "2026-10-20", type: "other", label: "Rest or 20min walk" },
          { date: "2026-10-21", type: "run", label: "Easy 6km, very easy", targetKm: 6 },
          { date: "2026-10-22", type: "run", label: "Easy 8km", targetKm: 8 },
          { date: "2026-10-23", type: "gymL", label: "Strength — light" },
          { date: "2026-10-23", type: "run", label: "Easy 6km", targetKm: 6 },
          { date: "2026-10-24", type: "run", label: "Trail 12km, easy, legs feeling out", targetKm: 12 },
          { date: "2026-10-25", type: "run", label: "Easy 8km", targetKm: 8 },
        ],
      },
    ],
  },
  {
    id: "op5",
    name: "Peak Volume",
    range: "26 Oct – 8 Nov",
    note: "The two biggest weeks of the programme. Week 11's long run is a full race simulation — closest we'll get to Kosci-day vert and duration before the taper begins.",
    weeks: [
      {
        id: "ow10",
        label: "Week 10",
        dateRange: "26 Oct – 1 Nov",
        sessions: [
          { date: "2026-10-26", type: "rest", label: "Rest" },
          { date: "2026-10-27", type: "run", label: "Run 12km w/ 5×3min tempo @ ~4:35/km", targetKm: 12 },
          { date: "2026-10-28", type: "gymL", label: "Strength — lower + core" },
          { date: "2026-10-28", type: "run", label: "Easy 8km", targetKm: 8 },
          { date: "2026-10-29", type: "run", label: "Trail 12km — downhill cadence drill", targetKm: 12 },
          { date: "2026-10-30", type: "rest", label: "Rest" },
          { date: "2026-10-31", type: "long", label: "Long trail 30km, ~900m vert — PH1000 + carb protocol", targetKm: 30 },
          { date: "2026-11-01", type: "long", label: "Back-to-back: trail 18km, tired legs", targetKm: 18 },
        ],
      },
      {
        id: "ow11",
        label: "Week 11 — race simulation",
        dateRange: "2–8 Nov",
        sessions: [
          { date: "2026-11-02", type: "rest", label: "Rest" },
          { date: "2026-11-03", type: "run", label: "Run 12km, easy", targetKm: 12 },
          { date: "2026-11-04", type: "gymU", label: "Strength — upper + core" },
          { date: "2026-11-04", type: "run", label: "Easy 8km", targetKm: 8 },
          { date: "2026-11-05", type: "run", label: "Trail 10km — downhill cadence drill, easy ahead of Sat", targetKm: 10 },
          { date: "2026-11-06", type: "other", label: "Rest, kit + fuel prep" },
          { date: "2026-11-07", type: "long", label: "Race simulation: trail 36km, ~3200m cumulative vert — full sub-15 pacing + fuel rehearsal", targetKm: 36 },
          { date: "2026-11-08", type: "long", label: "Back-to-back: easy 20km, tired legs", targetKm: 20 },
        ],
      },
    ],
  },
  {
    id: "op6",
    name: "Taper",
    range: "9 – 22 Nov",
    note: "Volume drops fast, intensity stays sharp in small doses. Legs should feel increasingly fresh each week — resist the urge to add anything extra here.",
    weeks: [
      {
        id: "ow12",
        label: "Week 12",
        dateRange: "9–15 Nov",
        sessions: [
          { date: "2026-11-09", type: "rest", label: "Rest" },
          { date: "2026-11-10", type: "run", label: "Run 8km w/ 4×90sec hill reps", targetKm: 8 },
          { date: "2026-11-11", type: "gymL", label: "Strength — light maintenance" },
          { date: "2026-11-11", type: "run", label: "Easy 6km", targetKm: 6 },
          { date: "2026-11-12", type: "run", label: "Trail 8km — downhill cadence drill, short and sharp", targetKm: 8 },
          { date: "2026-11-13", type: "rest", label: "Rest" },
          { date: "2026-11-14", type: "long", label: "Long trail 22km, easy — dial in race-day fuel timing", targetKm: 22 },
          { date: "2026-11-15", type: "run", label: "Easy 10km", targetKm: 10 },
        ],
      },
      {
        id: "ow13",
        label: "Week 13 — deep taper",
        dateRange: "16–22 Nov",
        sessions: [
          { date: "2026-11-16", type: "rest", label: "Rest" },
          { date: "2026-11-17", type: "run", label: "Run 6km w/ 4×2min strides", targetKm: 6 },
          { date: "2026-11-18", type: "rest", label: "Rest" },
          { date: "2026-11-19", type: "run", label: "Easy 6km, flat", targetKm: 6 },
          { date: "2026-11-20", type: "rest", label: "Rest" },
          { date: "2026-11-21", type: "run", label: "Easy trail 15km, comfortable pace only", targetKm: 15 },
          { date: "2026-11-22", type: "run", label: "Easy 8km", targetKm: 8 },
        ],
      },
    ],
  },
  {
    id: "op7",
    name: "Race Week",
    range: "23 – 27 Nov",
    note: "Minimal volume, maximum readiness. Short shakeouts only — the work is already banked. Shared sub-15h target with Shannon — target moving time ~14:30, splits from a 7:47am start: CP1 16.2km ~10:03am · CP2 40.3km (via Kosci summit) ~1:37pm · CP3 50.1km ~2:55pm · CP4 62.3km ~4:35pm · CP5 74.9km ~5:56pm (top of the big descent) · CP6 82.5km ~6:42pm (valley flat — fastest km of the day) · CP7 93.9km ~8:19pm · WP 104km ~9:55pm · Finish ~10:33pm. That's ~14h46m with aid stops — a buffer of roughly 14min under cutoff. Bank time on the CP4→CP5 descent and the CP5→CP6 flat, not on the two climbs bookending the Kosci summit.",
    weeks: [
      {
        id: "ow14",
        label: "Week 14 — race week",
        dateRange: "23–27 Nov",
        sessions: [
          { date: "2026-11-23", type: "run", label: "Easy 20min shakeout, 3×20sec strides", targetMin: 20 },
          { date: "2026-11-24", type: "run", label: "Easy 20min shakeout", targetMin: 20 },
          { date: "2026-11-25", type: "other", label: "Rest, gear + drop-bag check" },
          { date: "2026-11-26", type: "other", label: "Rest, travel to Thredbo, early night" },
          { date: "2026-11-27", type: "race", label: "Kosci100 — Blue group, 7:47am start. Sub-15 goal, sub-16 fallback.", targetKm: 100 },
        ],
      },
    ],
  },
];
